version: '3.8'

services:
  streamlit-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./cache:/app/cache
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://optimizer:optimizer123@postgres:5432/optimizer_db
      - REDIS_URL=redis://redis:6379/0
      - AIRFLOW_URL=http://airflow-webserver:8080
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - ollama
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=optimizer
      - POSTGRES_PASSWORD=optimizer123
      - POSTGRES_DB=optimizer_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  # Airflow services
  airflow-webserver:
    image: apache/airflow:2.7.0
    command: webserver
    entrypoint: /opt/airflow/script/entrypoint.sh
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://optimizer:optimizer123@postgres:5432/optimizer_db
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
      - AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/script/entrypoint.sh:/opt/airflow/script/entrypoint.sh
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.7.0
    command: scheduler
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql://optimizer:optimizer123@postgres:5432/optimizer_db
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=true
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK=true
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  ollama_data: